/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package per.sunmes.kfat.ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import per.sunmes.kfat.data.AnimationProjectInfo;
import per.sunmes.kfat.sys.SysData;

/**
 *
 * @author Administrator
 */
public class CreateProjectFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreateProjectFrame
     */
    public CreateProjectFrame() {
        initComponents();

        String oldPath = SysData.instance().getApplicationConfig().newProjectPath;
        if (oldPath.length() > 1) {
            workPositionFiled.setText(oldPath);
            pathChooser.setCurrentDirectory(new File(oldPath));
        }

    }

    private MainFrame mf;

    public void setBlockFrame(MainFrame mf) {
        this.mf = mf;
        this.setLocation(mf.getX() + (mf.getWidth() - this.getWidth()) / 2, mf.getY() + (mf.getHeight() - this.getHeight()) / 2);
    }

    public MainFrame getBlockFrame() {
        return mf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        projectNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        workPositionFiled = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        pathChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("新建项目");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jLabel1.setText("项目名称:");

        projectNameField.setText("NewProject");
        projectNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                projectNameFieldFocusLost(evt);
            }
        });

        jLabel2.setText("存储位置:");

        workPositionFiled.setText("H:\\Res\\TestATOOL");

        jButton1.setText("浏览");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("确定");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("取消");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(workPositionFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(projectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(workPositionFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (mf != null) {
            mf.setEnabled(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        File dir = new File(workPositionFiled.getText());
        if (!dir.exists()) {
            int result = JOptionPane.showConfirmDialog(this, "当前目录不存在,是否创建?", "提示", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(this, "请指定其它目录.");
                return;
            }
            if (!dir.mkdirs()) {
                JOptionPane.showMessageDialog(this, "目录创建失败!请确认有效路径!");
                return;
            }
        } else if (dir.isFile()) {
            dir.mkdir();
        }

        SysData.instance().getApplicationConfig().newProjectPath = dir.getAbsolutePath();

        dir = new File(dir.getAbsoluteFile() + "/" + projectNameField.getText());
        dir.mkdir();

        File childDir = new File(dir.getAbsolutePath() + "/res");
        if (!childDir.exists() || childDir.isFile()) {
            childDir.mkdir();
        }
        childDir = new File(dir.getAbsolutePath() + "/out");
        if (!childDir.exists() || childDir.isFile()) {
            childDir.mkdir();
        }

        AnimationProjectInfo projectInfo = new AnimationProjectInfo();
        projectInfo.name = projectNameField.getText();
        projectInfo.projectDirectory = dir.getAbsolutePath();
        SysData.instance().setProject(projectInfo);
        if (mf != null) {
            mf.updateProject();
            mf.setEnabled(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        if (mf != null) {
            requestFocus();
        }
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (mf != null) {
            mf.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void projectNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectNameFieldFocusLost
        if (projectNameField.getText().isEmpty()) {
            projectNameField.setText("NewProject");
        }
    }//GEN-LAST:event_projectNameFieldFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (pathChooser.showOpenDialog(this) == JFileChooser.OPEN_DIALOG) {
            workPositionFiled.setText(pathChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFileChooser pathChooser;
    private javax.swing.JTextField projectNameField;
    private javax.swing.JTextField workPositionFiled;
    // End of variables declaration//GEN-END:variables
}
